In [2]:
import numpy as np

In [ ]:
#creating arrays:
arr=np.array([1,1.23,'hello'])

In [ ]:
arr
#arrays can have only 1 type of data in it (helps faster execution)

array(['1', '1.23', 'hello'], dtype='<U32')

In [3]:
arrays=np.array([[1,2,3],[4,5,6]])
arrays

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.arange(1,12) #to generate an array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
#linear spacing
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
#RANDOM GENERATION FUNCTIONS

In [19]:
import random

In [27]:
np.random.randint((50))

39

In [28]:
np.random.randn(10)

array([ 0.33251385,  0.7500359 , -0.25022253,  0.23056101, -0.37792119,
       -0.22535528, -0.37084891, -1.1424301 , -1.68385812, -0.3077821 ])

In [ ]:
#ARRAY ATTRIBUTE AND METHODS



In [35]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr.shape

(3, 3)

In [38]:
arr.dtype

dtype('int64')

In [ ]:
#array methods

In [41]:
arr.min()

np.int64(1)

In [44]:
arr.max()

np.int64(9)

In [43]:
arr.sum()

np.int64(45)

In [45]:
np.sum(arr,axis=0) #column wise sum

array([12, 15, 18])

In [46]:
np.sum(arr,axis=1) #row wise sum

array([ 6, 15, 24])

In [49]:
arr.mean()

np.float64(5.0)

In [50]:
arr.std()

np.float64(2.581988897471611)

In [51]:
arr.argmax() #index of max element

np.int64(8)

In [52]:
arr.argmin()

np.int64(0)

In [ ]:
#RESHAPING AND RESIZING

In [56]:
arr=np.arange(1,31)

In [63]:
arr=arr.reshape(5,6) #the prodcut should be equal to number of rows n columns
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

**Indexing** **and slicing**

In [71]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [72]:
arr[1:5]

array([12, 13, 14, 15])

In [ ]:
#slicing  a 2d matrix

In [88]:
arr=np.arange(1,31).reshape(6,5)
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [92]:
arr[0] #indexin of rows

array([1, 2, 3, 4, 5])

In [97]:
arr[5,4] #row,column to slice a single element

np.int64(30)

In [99]:
arr[0:2,1:3] #indexing random elements from diff rows n columns

array([[2, 3],
       [7, 8]])

In [100]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [102]:
arr[:,2] #slicing a column

array([ 3,  8, 13, 18, 23, 28])

In [ ]:
#boolean indexing

In [104]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [105]:
arr[1::2] #to slice even nos

array([12, 14, 16, 18, 20])

In [107]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [108]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# **Array** **operartions**

In [ ]:
#arithmetic operations

In [109]:
arr1=np.arange(1,6)
arr2=np.arange(6,11)

In [112]:
arr1+arr2

array([ 7,  9, 11, 13, 15])

In [113]:
arr1-arr2

array([-5, -5, -5, -5, -5])

In [114]:
arr2*arr1

array([ 6, 14, 24, 36, 50])

In [115]:
arr1/arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [116]:
arr1//arr2

array([0, 0, 0, 0, 0])

In [118]:
arr1**arr2

array([      1,     128,    6561,  262144, 9765625])

In [119]:
l1=[10,20,30,40]
arr=np.array(l1)

In [121]:
arr+10

array([20, 30, 40, 50])

In [124]:
(np.arange(1,26).reshape(5,5))+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [125]:
arr*2

array([20, 40, 60, 80])

In [ ]:
#deep and shallow copy

In [126]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [129]:
slice=a[:5]
slice*10

array([10, 20, 30, 40, 50])

In [131]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [139]:
A=np.arange(1,5).reshape(2,2)
B=np.arange(5,9).reshape(2,2)
print(A,B)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]


In [140]:
A@B #MATRIX MULTIPLY

array([[19, 22],
       [43, 50]])

In [141]:
np.dot(A,B) #dot product

array([[19, 22],
       [43, 50]])

In [142]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [143]:
#STACKING ARRAY

In [147]:
a=np.array([1,2])
b=np.array([3,4])

In [149]:
np.vstack((a,b))

array([[1, 2],
       [3, 4]])

In [150]:
np.hstack((a,b))

array([1, 2, 3, 4])

In [151]:
np.column_stack((a,b))

array([[1, 3],
       [2, 4]])

In [152]:
#splitting array

In [154]:
c=np.arange(16).reshape(4,4)

In [158]:
d=np.vsplit(c,4)
for i in d:
  print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
